In [1]:
import nltk
nltk.download("twitter_samples")

[nltk]

[nltk_data] Downloading package twitter_samples to
[nltk_data]     C:\Users\tteru\AppData\Roaming\nltk_data...
[nltk_data]   Package twitter_samples is already up-to-date!

In [2]:
import pandas as pd
tweets = nltk.corpus.twitter_samples.strings()

In [3]:
df = pd.DataFrame(tweets, columns=["tweet"])[:10]

In [6]:
df.head()

                                               tweet clean_text
0                                hopeless for tmr :(         ss
1  Everything in the kids section of IKEA is so c...     ssssss
2  @Hegelbon That heart sliding into the waste ba...       swss
3  “@ketchBurning: I hate Japanese call him "bani...          s
4           Dang starting next week I have "work" :(        sww

In [ ]:
import re

def clean_text(text):
    text = text.lower()
    text = re.sub(r"http\\S+", "", text)
    text = re.sub(r"<.*?>", "", text)
    text = re.sub(r"[^\\w\\s]", "", text)
    text = re.sub(r)
    return text

df["clean_text"] = df["tweet"].apply(clean_text)

In [5]:
import spacy
npl = spacy.load("en_core_web_sm")

In [7]:
doc = npl("Los gatos estaban corriendo rápidamente")

In [8]:
def tokenize_text(text):
    [token.lemma_ for token in doc if not token.is_stop]
df["clean_text"] = df["tweet"].apply(tokenize_text)

In [9]:
df

                                               tweet clean_text
0                                hopeless for tmr :(       None
1  Everything in the kids section of IKEA is so c...       None
2  @Hegelbon That heart sliding into the waste ba...       None
3  “@ketchBurning: I hate Japanese call him "bani...       None
4           Dang starting next week I have "work" :(       None
5  oh god, my babies' faces :( https://t.co/9fcwG...       None
6                  @RileyMcDonough make me smile :((       None
7  @f0ggstar @stuartthull work neighbour on motor...       None
8  why?:("@tahuodyy: sialan:( https://t.co/Hv1i0x...       None
9  Athabasca glacier was there in #1948 :-( #atha...       None